name: 'Print backend hashes'

on: [workflow_dispatch]

jobs:
  print-backend-sha:
    runs-on: mempool-ci
    name: Print backend hashes
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: repo

      - name: Run script
        working-directory: repo
        run: |
          chmod +x ./scripts/get_backend_hash.sh
          sh ./scripts/get_backend_hash.sh
